name: 'Validate'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  ENV_FILE: .env

jobs:

  validate:
    name: 'Test and lint'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.x ]
    runs-on: ${{ matrix.os }}
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v2

      # see https://github.com/actions/runner/issues/655
      - name: Import environment variables from .env
        id: import-env
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < ${{ env.ENV_FILE }}

      - name: 'Make all scripts executable'
        if: runner.os == 'Linux'
        run: chmod +x ${{ env.SCRIPTS_ROOT }}/*

      - name: Prepare and describe working environment
        run: ${{ env.SCRIPTS_ROOT }}/setup-env-linux.sh

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Stage Python environment
        run: |
          pip install pipenv
          pipenv --where --venv --py --envs --support install --three --dev
          pipenv graph

      - name: 'Run tests (unittest)'
        run: pipenv run python -m unittest discover --start-directory 'tests' --pattern 'Test*.py' --verbose --locals

      - name: 'Run linter (pylint)'
        run: pipenv run pylint xhoundpi
