name: 'Validate'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  PIPENV_VENV_IN_PROJECT: 1

jobs:

  #TODO consolidate options (versions, os, etc. into variables across jobs)

  test:
    name: 'Test and lint'
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.x"]
    runs-on: ${{ matrix.os }}
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: Prepare and describe environment
        run: |
          echo "Preparing '$RUNNER_OS' environment"
          if [ "$RUNNER_OS" == "Linux" ]; then
            SUDO=sudo
            if [ "$GITHUB_ACTOR" == "nektos/act" ]; then
              echo "Running in 'act' container, not using sudo"
              SUDO=""
            fi
            printenv

            $SUDO apt update
            $SUDO apt install -y \
              tree \

            tree -Dphug
          elif [ "$RUNNER_OS" == "Windows" ]; then
            printenv
            cmd //c "tree /f /a"
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Prepare environment
        run: |
          pip install pipenv
          pipenv --where --venv --py --envs --support install --three --dev

      - name: 'Run tests (unittest)'
        run: pipenv run python -m unittest discover --start-directory 'tests' --pattern 'Test*.py' --verbose --locals

      - name: 'Run linter (pylint)'
        run: pipenv run pylint xhoundpi